name: GenShinCardDraw
main: org.qiuhua.genshincarddraw.Main
version: 1.0.0
api-version: 1.13
depend:
  - PlaceholderAPI
  - UnrealCore
  - UnrealGUIPro
softdepend:
  - NeigeItems
  - Vault
  - PlayerPoints
commands:
  GenShinCardDraw:
    description: "主指令"
    usage: /<command>
libraries:
  - com.google.code.gson:gson:2.10.1
  - com.zaxxer:HikariCP:4.0.3
  - org.apache.commons:commons-math3:3.6.1